weppro/Models/Contxt.cs
using Microsoft.EntityFrameworkCore;

namespace weppro.Models
{
    public class Contxt : DbContext
    {
        public Contxt(DbContextOptions<Contxt> options)
            : base(options) { }

        public DbSet<infos> Infostep1 { get; set; }

    }

}

weppro/Models/ErrorViewModel.cs
namespace weppro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

weppro/Models/infos.cs
using System.ComponentModel.DataAnnotations;

namespace weppro.Models

{
    public class infos
{

    public int Steps { get; set; }
    [Key]
        public DateTime Date { get; set; }
    }
}

weppro/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using weppro.Models;

namespace weppro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

weppro/Controllers/PedometerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using weppro.Models;
namespace weppro.Controllers
{
    public class PedometerController : Controller
    {
        private Contxt _Contxt;
        public PedometerController (Contxt contxt)
        {
            _Contxt = contxt; 
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Steps()
        {
            return View();
        }
         [HttpPost]
        public IActionResult StepsToCalories(infos NumOfSteps)
        {
            NumOfSteps.Date = DateTime.Now;
            double TotalCaloriesBurned = NumOfSteps.Steps * 0.04;

            _Contxt.Infostep1.Add(NumOfSteps);
            _Contxt.SaveChanges();

             return View(TotalCaloriesBurned);

        }

    }
}

weppro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p> @Html.ActionLink("Steps to Calories Calculator","Steps","Pedometer")</p>
</div>

weppro/Views/Pedometer/Steps.cshtml
   <h1 class="cen"> Write down the number of steps you took</h1>

<form class="all" asp-action="StepsToCalories" asp-controller="Pedometer" method ="post">
   <br />
    <input  type="number" name="Steps"class="txt" />
    <br />
    <button type ="submit" class="bt">Calculate</button >

</form>

weppro/Views/Pedometer/StepsToCalories.cshtml
@model double

<h2 class="cen">Calories Burned</h2>
<h1 class="cen">@Model</h1>

weppro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - weppro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/weppro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">weppro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedometer" asp-action="Steps">Steps</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - omar maasher - <a asp-area="" asp-controller="Pedometer" asp-action="Steps">Steps</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>